### PR TITLE
to support printing 'utf-8', including normal set of, characters

### PR DESCRIPTION
**Pull request by justinyhuang**

### CODE REVIEW

**Comment by laktak** [comment]
Thank you for your PR! 

Could you please describe the problem you are trying to solve and add a testcase? I'm guessing it's for Python 2 only as it adds `b'...'` to the output on Python 3.

**Comment by justinyhuang** [comment]
Sure. So I use powerline patched fonts in my terminal and the plugin will receive special characters from tmux. you may see it in the picture here.with the change I make the print command is able to output those characters without error. i am not a Python expert so if you see a better way to do that I will be more than happy to learn =)
please let me know if it makes sense, or I can provide any more details.
cheers,Justin
    On Friday, November 17, 2017, 12:36:55 PM MST, Christian Zangl <notifications@github.com> wrote:  
 
 
Thank you for your PR!

Could you please describe the problem you are trying to solve and add a testcase? I'm guessing it's for Python 2 only as it adds b'...' to the output on Python 3.

**Comment by frodeaa** [comment]
I'm using Python 2

    $ python --version
    Python 2.7.10

and without the fix the plugin will fail with UnicodeEncodeError
if the tmux buffer contains non ascii characters

    UnicodeEncodeError: 'ascii' codec can't encode character u'\xe5' in position 5: ordinal

**Comment by laktak** [comment]
OK, I've changed this so it works with Python 2 and 3. I've also added some tests and excluded Powerline symbols from the result set. Let me know if this works for you!

**Comment by frodeaa** [comment]
@laktak it works for me!

**Comment by justinyhuang** [comment]
works for me, too! 
thank you for making the change. i will abandon the PR.

**Pull request closed without merging**
