### PR TITLE
preserve fzf query across ctrl+{f,g} cycles

### PR DESCRIPTION
**Pull request by laur89**

### CODE REVIEW

**Comment by laur89** [comment]
After (and _if_) this gets merged, I propose following PRs:

https://github.com/laur89/extrakto/tree/feature/remove-recursion
https://github.com/laur89/extrakto/tree/feature/sh-cleanup
https://github.com/laur89/extrakto/tree/feature/colorize-fzf-hdr

**Comment by laktak** [comment]
Thank you, this works great!

You are welcome to submit your other PRs as well.

Only for the *sh-cleanup* please keep the lowercase variable names (https://unix.stackexchange.com/a/42849/46158 suggest to use lower case to avoid conflicts with env. variables).

**Comment by laur89** [comment]
Would you consider some other format for global vars? Maybe camel-case?

**Comment by laktak** [comment]
We could add an `opt_` prefix for the options, so e.g. `opt_grab_area` instead of `grab_area`.

**Pull request merged**
