### PR TITLE
added fzf preview flags

### PR DESCRIPTION
**Pull request by cibinmathew**
I tried to create a variable to receive simple preview commands #65

### CODE REVIEW

**Comment by laktak** [comment]
Thank you for taking the time to create a PR but I still don't quite understand what problem you are trying to solve.

The preview will only work if you select a full path. Are you using this in a different way? Otherwise I think the use case is quite small and can be solved with the workaround I showed you in #65.

**Comment by cibinmathew** [comment]
Some sample previews I use now (it prints the content if a file and directory structure if dir). Trying to fallback to just print if everything fails. 
```
set -g @extrakto_fzf_preview "(cat {} || tree -C {}) 2> /dev/null"
set -g @extrakto_fzf_preview "(highlight -O ansi -l {} || coderay {} || cat {} || tree -C {}) 2> /dev/null | head -100"

```

If you see useful snippets, please share

**Comment by cibinmathew** [comment]
Here is what I tried. 
I changed 'fzf' to '/path/to/my/script.sh'. But it wasn't able to receive the selection for preview command without a change in the base code.

```
    out="$(get_cap \
        | /path/to/my/script.sh \   <-- here there is no placeholder to send  selection to the custom script
            --print-query \
            --query="$query" \
```

But inside /path/to/my/script.sh, we have **{}** which will need the selection to be explicitly passed to script
fzf --preview='cat {} || tree -C {}'  "$@"

TIA

**Comment by laktak** [comment]
> Here is what I tried.
> I changed 'fzf' to '/path/to/my/script.sh'. But it wasn't able to receive the selection for preview command without a change in the base code.

I don't understand what you mean with that. 

I created `~/preview.sh`:
```
fzf --preview='cat {} || tree -C {}' "$@"
```
Ran:
```
chmod +x ~/preview.sh
tmux set -g @extrakto_fzf_tool "$HOME/preview.sh"
```

And the preview works if I select a file/dir with a full path. It does not work with relative paths.

What does not work for you with that setup?

**Comment by cibinmathew** [comment]
Thanks @laktak this worked :-)

I noticed relative paths worked only when they are relative to that working dir of the pane when it started (if we cd to a diff dir and print using ls, it never worked). 
Do you think there is a way for the script every time to pick up the working dir of the current pane when hotkey is trigerred.

Closing the issue as it worked.

**Comment by laktak** [comment]
>  Do you think there is a way for the script every time to pick up the working dir of the current pane when hotkey is trigerred.

I don't think that this would really solve the issue. Your pane can contain relative paths for one directory, then you cd somewhere else and have different relative paths from that directory. There is no way that extrakto can figure that out.

**Pull request closed without merging**
