### PR TITLE
bash cleanup

### PR DESCRIPTION
**Pull request by laur89**
- minor bash cleanup, such as:
    - variable localization
    - use bash syntax (eg [[]] vs [])
    - improve param quoting

### CODE REVIEW

**Comment by laktak** [comment]
Thanks!

What issues do you mean in this comment? 

```
# note we use the superfluous 'local' keyword in front of 'captured' var;
# without it we get intermittent issues with extracto python script (when reading stdin);
```

**Comment by laur89** [comment]
> What issues do you mean in this comment?

Remove `local` prefix from lines 60 & 66 and cycle through ctrl+{f,g}.
It's really odd why it makes a difference, but it does. Additionally try adding `echo "$captured" >> /tmp/capture` on line 67 (ie log out the result somewhere) and check it out - unicode characters are all messed up.

**Comment by laur89** [comment]
Should we maybe open an issue for this?

**Comment by laktak** [comment]
I can't reproduce those issues on GNU bash, version 5.0.18(1)-release (x86_64-pc-linux-gnu)

Can you try initializing `captured`?
```
    local pane captured
    captured=""
```

**Comment by laur89** [comment]
Event weirder, it no longer reproduces, with or without the var initialization.

**Comment by laktak** [comment]
OK, I'll add the initialization for now. Let me know if it shows up again.

**Pull request merged**
